# Generated by Django 5.1.4 on 2024-12-18 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Mano', 'En Mano'), ('Reserva', 'En Reserva')], default='Mano', max_length=10)),
                ('superviviente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='zombies.superviviente')),
            ],
        ),
    ]
