# Generated by Django 5.1.4 on 2025-01-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombies', '0002_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.CharField(max_length=100, unique=True)),
                ('supervivientes', models.ManyToManyField(blank=True, related_name='partidas', to='zombies.superviviente')),
            ],
        ),
    ]
