# Generated by Django 5.1.4 on 2025-01-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombies', '0004_superviviente_vivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
