# Generated by Django 5.1.4 on 2025-01-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombies', '0005_partida_finalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superviviente',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
