# Generated by Django 5.1.4 on 2025-01-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombies', '0006_alter_superviviente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='nivel',
            field=models.CharField(choices=[('Azul', 'Azul'), ('Amarillo', 'Amarillo'), ('Naranja', 'Naranja'), ('Rojo', 'Rojo')], default='Azul', max_length=50),
        ),
    ]
